version: '3.6'
networks:
  chirpstack:
    driver: overlay
    attachable: true
services:
  mosquitto:
    image: localhost:5000/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
        - chirpstack
