FROM debian:bookworm

ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt dist-upgrade -y 
RUN apt install wget -y
RUN apt install build-essential -y
RUN apt install libwrap0-dev libssl-dev libc-ares-dev uuid-dev -y

RUN mkdir -p /usr/local/src
WORKDIR /usr/local/src
RUN wget --no-check-certificate http://mosquitto.org/files/source/mosquitto-1.4.10.tar.gz
RUN tar -xvzf ./mosquitto-1.4.10.tar.gz
WORKDIR /usr/local/src/mosquitto-1.4.10
RUN make
RUN make install
RUN adduser --system --disabled-password --disabled-login mosquitto
USER mosquitto
EXPOSE 1883 9001
CMD ["/usr/local/sbin/mosquitto"]
